#!/usr/bin/env Rscript
# Six-state (2x3) continuous official NicheNet weighted-LR Circos panel.
script_file <- sub('^--file=', '', grep('^--file=', commandArgs(trailingOnly=FALSE), value=TRUE)[1])
script_dir <- dirname(normalizePath(script_file)); final_root <- normalizePath(file.path(script_dir, '..', '..', '..', '..')); data_root <- dirname(final_root)
.libPaths(c(file.path(data_root, 'Rlib_nichenet_vis'), .libPaths()))
suppressPackageStartupMessages({library(dplyr);library(tibble);library(purrr);library(magrittr);library(circlize);library(grid);library(png)})
root <- file.path(data_root, 'nichenet', 'new_interpolation', 'latest_nichenet'); src <- file.path(dirname(script_dir), 'nichenetr_official_R')
source(file.path(src,'application_prediction.R'));source(file.path(src,'application_visualization.R'))
out <- file.path(root,'figures','official_weighted_lr_circos_six_states_20260827'); dat <- file.path(root,'data','official_weighted_lr_circos_six_states_20260827')
dir.create(out,recursive=TRUE,showWarnings=FALSE);dir.create(dat,recursive=TRUE,showWarnings=FALSE)
weighted <- readRDS(file.path(root,'external_data','weighted_networks_nsga2r_final_mouse.rds'))
pairs <- read.csv(file.path(root,'data','candidate_ligand_receptor_pairs.csv'))
lr <- pairs %>% transmute(from=ligand,to=receptor) %>% distinct(); expr <- read.csv(file.path(root,'data','model_expression_summary_51_states.csv')); act <- read.csv(file.path(root,'results','official_ligand_activity_all_50_windows.csv'))
states <- data.frame(model_time=c(.3,.6,.9,1.2,1.5,1.8),age=c(3.46,4.42,5.38,8.14,11.80,15.46),window=c('t0p25_to_t0p30','t0p55_to_t0p60','t0p85_to_t0p90','t1p15_to_t1p20','t1p45_to_t1p50','t1p75_to_t1p80'),label=c('t0p30','t0p60','t0p90','t1p20','t1p50','t1p80'))
sender_type <- function(time,ligands) expr %>% filter(abs(model_time-time)<1e-8,gene%in%ligands,pct_positive>=.10) %>% arrange(gene,desc(pct_positive),desc(mean_log1p)) %>% group_by(gene) %>% slice(1) %>% ungroup() %>% transmute(ligand=gene,ligand_type=celltype)
all_links <- list(); image_paths <- character(nrow(states))
for(i in seq_len(nrow(states))) {st<-states[i,];top<-act %>% filter(window==st$window) %>% arrange(activity_rank) %>% slice_head(n=12) %>% pull(test_ligand);rec<-expr %>% filter(abs(model_time-st$model_time)<1e-8,celltype=='Microglia',gene%in%pairs$receptor,pct_positive>.05) %>% pull(gene) %>% unique();wl<-get_weighted_ligand_receptor_links(best_upstream_ligands=top,expressed_receptors=rec,lr_network=lr,weighted_networks_lr_sig=weighted$lr_sig);links<-wl %>% transmute(ligand=from,target=to,weight=weight) %>% inner_join(sender_type(st$model_time,top),by='ligand') %>% mutate(target_type='Microglia receptor') %>% distinct(ligand,target,ligand_type,target_type,.keep_all=TRUE);if(nrow(links)==0)stop(paste('No links',st$label));write.csv(links,file.path(dat,paste0('official_weighted_lr_links_',st$label,'.csv')),row.names=FALSE);types<-unique(links$ligand_type);cp<-grDevices::hcl.colors(length(types),'Dark 3');names(cp)<-types;vis<-prepare_circos_visualization(links,ligand_colors=cp,target_colors=c('Microglia receptor'='#B2182B'));attr(vis$links_circle,'cutoff_include_all_ligands')<-min(vis$links_circle$weight);fn<-file.path(out,paste0('official_weighted_lr_circos_',st$label,'.png'));png(fn,width=1800,height=1800,res=230);circos.clear();make_circos_plot(vis,transparency=TRUE,args.circos.text=list(cex=.56));title(sprintf('t=%.1f (%.2f months)',st$model_time,st$age),cex.main=.95);circos.clear();dev.off();cairo_pdf(sub('png$','pdf',fn),width=7.2,height=7.2);circos.clear();make_circos_plot(vis,transparency=TRUE,args.circos.text=list(cex=.56));title(sprintf('t=%.1f (%.2f months)',st$model_time,st$age),cex.main=.95);circos.clear();dev.off();links$model_time<-st$model_time;links$age_months<-st$age;links$window<-st$window;all_links[[st$label]]<-links;image_paths[i]<-fn}
draw_grid <- function(){grid.newpage();lay<-grid.layout(2,3);pushViewport(viewport(layout=lay));for(i in seq_along(image_paths))grid.raster(readPNG(image_paths[i]),vp=viewport(layout.pos.row=ifelse(i<=3,1,2),layout.pos.col=((i-1)%%3)+1));popViewport()}
png(file.path(out,'official_weighted_lr_circos_six_states_2x3.png'),width=4800,height=3200,res=300);draw_grid();dev.off();pdf(file.path(out,'official_weighted_lr_circos_six_states_2x3.pdf'),width=16,height=10.7);draw_grid();dev.off()
write.csv(bind_rows(all_links),file.path(dat,'all_six_state_official_weighted_lr_links.csv'),row.names=FALSE)
writeLines(c('2x3 panel uses official NicheNet get_weighted_ligand_receptor_links(), prepare_circos_visualization(), and make_circos_plot().','Top ligands are selected from current latest_nichenet official activity results.','Weights are NicheNet LR prior weights; they are not CytoBridge attention or measured binding strength.'),file.path(out,'README.txt'))
