"""Tool-layer public API."""

from . import core
from . import downstream
from . import graph
from . import train

try:
    from .core import flow_matching
except ModuleNotFoundError as exc:
    if exc.name in {"ot"}:
        flow_matching = None
    else:
        raise

try:
    from .core import methods
except ModuleNotFoundError as exc:
    if exc.name in {"torchdiffeq"}:
        methods = None
    else:
        raise

try:
    from .downstream import analysis
except ModuleNotFoundError as exc:
    if exc.name in {"anndata", "scanpy"}:
        analysis = None
    else:
        raise

from .downstream import (
    AblationGifResult,
    AblationPanelSeriesResult,
    VirtualAblationResult,
    VirtualInteractionAblationResult,
    DynamicalRuntime,
    DevelopmentalWaveResult,
    DistributionEvaluationResult,
    DistributionMetricComparison,
    GeneProgramPanelResult,
    GeneSetLibrary,
    GrowthInteractionSummary,
    FrozenBenchmarkTransform,
    evaluate_growth_by_timepoint,
    InterpolationResult,
    LRMultipanelSpec,
    LRPanelResult,
    FocalLRTypeHotspotResult,
    LRTemporalProjectionResult,
    LoadedClassifierCache,
    LoadedModel,
    MLP,
    PCAAnchorReconstructionQCResult,
    PCAReconstructionSpec,
    TemporalGenePatternResult,
    TemporalProfileClusteringResult,
    VelocityEmbeddingProjectionResult,
    adata_to_aligned_dataframe,
    analyze_attention_by_celltype,
    analyze_spatial_label_sensitivity,
    analyze_developmental_wave,
    apply_spatial_warp_to_segments,
    collect_top_variable_heatmaps,
    build_dynamical_runtime,
    build_cached_classifier_inputs_from_adata,
    build_time_grid,
    compute_drift,
    compute_drift_from_adata,
    compare_distribution_metric_tables,
    benchmark_projection_seed,
    compute_distribution_metrics,
    compute_generated_vs_observed_plot_limits,
    compute_local_structure_metrics,
    compute_timepoint_communications,
    compute_umap_embedding,
    compute_velocity_components,
    compute_velocity_components_from_adata,
    compute_virtual_ablation_metrics,
    cluster_temporal_profiles,
    copy_if_needed,
    crop_ablation_panel,
    export_ablation_gifs,
    export_ablation_panel_series,
    evaluate_pca_anchor_reconstruction,
    evaluate_model_distributions,
    evaluate_spatiotemporal_prediction,
    fit_frozen_benchmark_transform,
    infer_feature_columns,
    infer_time_key,
    infer_pca_center,
    inverse_pca_states,
    load_pca_reconstruction_spec,
    load_cached_mlp_classifier,
    load_dynamical_model_from_dir,
    load_legacy_dynamical_model_from_dir,
    load_label_to_color,
    load_gmt_gene_sets,
    load_ligand_receptor_database,
    merge_annotation,
    model_state_adata,
    make_pca_reconstruction_spec,
    pca_reconstruction_feature_coverage,
    make_gene_set_library,
    parse_time_value,
    overrepresentation_analysis,
    predict_cached_mlp_classifier_from_adata,
    predict_labels_for_points,
    predict_labels_for_trajectories,
    select_spatial_smoothing_k,
    train_cached_mlp_classifier_from_adata,
    plot_generated_vs_observed,
    plot_lineage_sankey,
    plot_spatiotemporal_3d,
    compute_focal_lr_type_hotspots,
    project_communication_to_lr_timecourses,
    project_velocity_to_embedding,
    render_lr_expression_panels,
    render_lr_incoming_multipanel,
    render_top_receivers_barplot,
    run_interpolation_workflow,
    run_virtual_cell_type_ablation,
    run_virtual_interaction_ablation,
    sample_observed_x0,
    save_distribution_evaluation,
    save_distribution_metric_comparison,
    save_interpolated_attention,
    save_timepoint_snapshots,
    set_global_random_seed,
    simulate_sde_points,
    simulate_sde_points_split,
    simulate_sde_points_split_from_x0,
    simulate_piecewise_spatially_warped_split,
    smooth_spatial_labels,
    SpatialSmoothingSelection,
    simplify_gene_names,
    summarize_growth_interaction_by_celltype,
    summarize_label_composition,
    summarize_temporal_gene_patterns,
    train_mlp_classifier,
    train_mlp_classifier_from_adata,
)
from .graph import train_edge_predictor
from .train import fit, fit_spatial_csv, fit_spatial_h5ad

__all__ = [
    "analysis",
    "core",
    "downstream",
    "fit",
    "fit_spatial_csv",
    "fit_spatial_h5ad",
    "flow_matching",
    "graph",
    "methods",
    "train",
    "train_edge_predictor",
    "build_dynamical_runtime",
    "load_dynamical_model_from_dir",
    "load_legacy_dynamical_model_from_dir",
    "load_cached_mlp_classifier",
    "load_label_to_color",
    "load_gmt_gene_sets",
    "build_cached_classifier_inputs_from_adata",
    "DynamicalRuntime",
    "DevelopmentalWaveResult",
    "InterpolationResult",
    "LoadedModel",
    "LoadedClassifierCache",
    "SpatialSmoothingSelection",
    "apply_spatial_warp_to_segments",
    "AblationPanelSeriesResult",
    "AblationGifResult",
    "VirtualAblationResult",
    "VirtualInteractionAblationResult",
    "GeneProgramPanelResult",
    "GeneSetLibrary",
    "GrowthInteractionSummary",
    "FrozenBenchmarkTransform",
    "benchmark_projection_seed",
    "evaluate_spatiotemporal_prediction",
    "fit_frozen_benchmark_transform",
    "evaluate_growth_by_timepoint",
    "LRMultipanelSpec",
    "LRPanelResult",
    "FocalLRTypeHotspotResult",
    "LRTemporalProjectionResult",
    "PCAAnchorReconstructionQCResult",
    "PCAReconstructionSpec",
    "TemporalGenePatternResult",
    "TemporalProfileClusteringResult",
    "VelocityEmbeddingProjectionResult",
    "collect_top_variable_heatmaps",
    "copy_if_needed",
    "crop_ablation_panel",
    "export_ablation_gifs",
    "export_ablation_panel_series",
    "simulate_sde_points",
    "simulate_sde_points_split",
    "simulate_sde_points_split_from_x0",
    "simulate_piecewise_spatially_warped_split",
    "select_spatial_smoothing_k",
    "smooth_spatial_labels",
    "sample_observed_x0",
    "compute_velocity_components",
    "compute_velocity_components_from_adata",
    "project_velocity_to_embedding",
    "compute_virtual_ablation_metrics",
    "cluster_temporal_profiles",
    "evaluate_pca_anchor_reconstruction",
    "compute_drift",
    "compute_drift_from_adata",
    "compute_timepoint_communications",
    "compute_umap_embedding",
    "infer_pca_center",
    "inverse_pca_states",
    "load_pca_reconstruction_spec",
    "make_pca_reconstruction_spec",
    "pca_reconstruction_feature_coverage",
    "make_gene_set_library",
    "save_interpolated_attention",
    "save_timepoint_snapshots",
    "set_global_random_seed",
    "analyze_attention_by_celltype",
    "analyze_spatial_label_sensitivity",
    "analyze_developmental_wave",
    "train_mlp_classifier",
    "train_mlp_classifier_from_adata",
    "train_cached_mlp_classifier_from_adata",
    "predict_cached_mlp_classifier_from_adata",
    "predict_labels_for_points",
    "predict_labels_for_trajectories",
    "plot_lineage_sankey",
    "plot_spatiotemporal_3d",
    "render_lr_expression_panels",
    "render_lr_incoming_multipanel",
    "render_top_receivers_barplot",
    "load_ligand_receptor_database",
    "compute_focal_lr_type_hotspots",
    "project_communication_to_lr_timecourses",
    "run_interpolation_workflow",
    "run_virtual_cell_type_ablation",
    "run_virtual_interaction_ablation",
    "MLP",
    "parse_time_value",
    "overrepresentation_analysis",
    "infer_time_key",
    "adata_to_aligned_dataframe",
    "infer_feature_columns",
    "merge_annotation",
    "model_state_adata",
    "build_time_grid",
    "DistributionEvaluationResult",
    "DistributionMetricComparison",
    "compare_distribution_metric_tables",
    "compute_distribution_metrics",
    "compute_generated_vs_observed_plot_limits",
    "compute_local_structure_metrics",
    "evaluate_model_distributions",
    "plot_generated_vs_observed",
    "save_distribution_evaluation",
    "save_distribution_metric_comparison",
    "summarize_growth_interaction_by_celltype",
    "summarize_label_composition",
    "summarize_temporal_gene_patterns",
    "simplify_gene_names",
]
