"""Downstream analysis utilities."""

from .attention import analyze_attention_by_celltype, save_interpolated_attention
from .ablation import AblationPanelSeriesResult, crop_ablation_panel, export_ablation_panel_series
from .checkpoint import LoadedModel, load_dynamical_model_from_dir, load_legacy_dynamical_model_from_dir
from .classification import (
    build_cached_classifier_inputs_from_adata,
    LoadedClassifierCache,
    MLP,
    load_cached_mlp_classifier,
    predict_cached_mlp_classifier_from_adata,
    predict_labels_for_points,
    predict_labels_for_trajectories,
    train_mlp_classifier,
    train_mlp_classifier_from_adata,
)
from .downstream_data import (
    adata_to_aligned_dataframe,
    build_time_grid,
    infer_feature_columns,
    infer_time_key,
    merge_annotation,
    parse_time_value,
)
from .pipeline_utils import (
    downsample_xy,
    find_single_classifier_cache,
    parse_boolish,
    parse_csv_floats,
    parse_csv_floats_or_all,
    require_columns,
    resolve_split_sigma,
    select_evenly_spaced,
    set_global_random_seed,
)
from .gene_program import GeneProgramPanelResult, collect_top_variable_heatmaps
from .lr_panels import LRMultipanelSpec, LRPanelResult, copy_if_needed, render_lr_expression_panels, render_lr_incoming_multipanel, render_top_receivers_barplot
from .simulation import (
    apply_spatial_warp_to_segments,
    compute_drift,
    compute_drift_from_adata,
    compute_umap_embedding,
    compute_velocity_components,
    compute_velocity_components_from_adata,
    sample_observed_x0,
    simulate_sde_points,
    simulate_sde_points_split,
    simulate_sde_points_split_from_x0,
    simulate_piecewise_spatially_warped_split,
)
from .runtime import DynamicalRuntime, build_dynamical_runtime
from .visualization import load_label_to_color, save_timepoint_snapshots
from .workflows import (
    InterpolationResult,
    compute_timepoint_communications,
    plot_lineage_sankey,
    plot_spatiotemporal_3d,
    run_interpolation_workflow,
)

__all__ = [
    "DynamicalRuntime",
    "InterpolationResult",
    "LoadedClassifierCache",
    "LoadedModel",
    "AblationPanelSeriesResult",
    "crop_ablation_panel",
    "export_ablation_panel_series",
    "GeneProgramPanelResult",
    "collect_top_variable_heatmaps",
    "LRMultipanelSpec",
    "LRPanelResult",
    "render_lr_expression_panels",
    "render_lr_incoming_multipanel",
    "render_top_receivers_barplot",
    "copy_if_needed",
    "MLP",
    "adata_to_aligned_dataframe",
    "analyze_attention_by_celltype",
    "apply_spatial_warp_to_segments",
    "build_dynamical_runtime",
    "build_cached_classifier_inputs_from_adata",
    "build_time_grid",
    "compute_drift",
    "compute_drift_from_adata",
    "compute_timepoint_communications",
    "compute_umap_embedding",
    "compute_velocity_components",
    "compute_velocity_components_from_adata",
    "downsample_xy",
    "find_single_classifier_cache",
    "infer_feature_columns",
    "infer_time_key",
    "load_cached_mlp_classifier",
    "load_dynamical_model_from_dir",
    "load_legacy_dynamical_model_from_dir",
    "load_label_to_color",
    "merge_annotation",
    "parse_boolish",
    "parse_csv_floats",
    "parse_csv_floats_or_all",
    "parse_time_value",
    "predict_cached_mlp_classifier_from_adata",
    "predict_labels_for_points",
    "predict_labels_for_trajectories",
    "plot_lineage_sankey",
    "plot_spatiotemporal_3d",
    "require_columns",
    "resolve_split_sigma",
    "run_interpolation_workflow",
    "sample_observed_x0",
    "save_interpolated_attention",
    "save_timepoint_snapshots",
    "select_evenly_spaced",
    "set_global_random_seed",
    "simulate_sde_points",
    "simulate_sde_points_split",
    "simulate_sde_points_split_from_x0",
    "simulate_piecewise_spatially_warped_split",
    "train_mlp_classifier",
    "train_mlp_classifier_from_adata",
]
